modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${mod_license}"
showAsResourcePack=false

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
description='''${mod_description}'''
features = { java_version = "${java_version_range}" }
displayTest="MATCH_VERSION"
authors="${mod_authors}"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tetra"
mandatory=true
versionRange="[6.17.0]"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tacz"
mandatory=true
versionRange="[1.1.8-hotfix]"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mutil"
mandatory=true
versionRange="[6.3.0]"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
mandatory=false
versionRange="[15.20.0.106]"
ordering="AFTER"
side="CLIENT"
